import type { FeedGroup } from '~/types/feed'
// import { getFavicon, getGhAvatar, getGhIcon, getQqAvatar, QqAvatarSize } from './utils/img'

export default [
	{
		name: '『网上邻居』',
		desc: '',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '安知鱼',
				sitenick: '安知鱼',
				title: '安知鱼',
				desc: '生活明朗，万物可爱',
				link: 'https://blog.anheyu.com/',
				feed: '',
				icon: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				avatar: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				archs: ['Hexo', '服务器'],
				date: '2025-03-19',
				comment: '',
			},
			{
				author: '东方月初',
				sitenick: '东方月初',
				title: '东方月初',
				desc: '分享有趣但又无聊的东西。',
				link: 'https://blog.biuxin.com/',
				feed: 'https://blog.biuxin.com/atom.xml',
				icon: 'https://x.xinb.de/i/2024/09/19/040857.webp',
				avatar: 'https://x.xinb.de/i/2024/09/19/040857.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2025-08-29',
				comment: '',
			},
			{
				author: '梦爱吃鱼',
				sitenick: '梦爱吃鱼',
				title: '梦爱吃鱼',
				desc: '不负心灵，不负今生。',
				link: 'https://blog.bsgun.cn/',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
				avatar: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
				archs: ['Hexo', '服务器'],
				date: '2025-08-29',
				comment: '',
			},
			{
				author: 'APP喵',
				sitenick: 'APP喵',
				title: 'APP喵',
				desc: 'Telegram 频道与资源分享 频道主。',
				link: 'https://www.appmiu.com/',
				feed: '',
				icon: 'https://img.314926.xyz/images/2025/07/09/app喵.webp',
				avatar: 'https://img.314926.xyz/images/2025/07/09/app喵.webp',
				archs: ['服务器'],
				date: '2025-08-29',
				comment: '',
			},
			{
				author: 'DIYGOD',
				sitenick: 'DIYGOD',
				title: 'DIYGOD',
				desc: 'xlog和folo的大佬。',
				link: 'https://diygod.me/',
				feed: '',
				icon: 'https://avatars.githubusercontent.com/u/8266075?v=4',
				avatar: 'https://avatars.githubusercontent.com/u/8266075?v=4',
				archs: ['服务器'],
				date: '2025-08-29',
				comment: '',
			},
			{
				author: 'Akilarの糖果屋',
				sitenick: 'Akilarの糖果屋',
				title: 'Akilarの糖果屋',
				desc: '欢迎光临糖果屋。',
				link: 'https://akilar.top/',
				feed: 'https://akilar.top/atom.xml',
				icon: 'https://npm.elemecdn.com/akilar-friends@latest/avatar/akilar.top.jpg',
				avatar: 'https://npm.elemecdn.com/akilar-friends@latest/avatar/akilar.top.jpg',
				archs: ['服务器'],
				date: '2025-08-29',
				comment: '',
			},
			{
				author: '青桔气球',
				sitenick: '青桔气球',
				title: '青桔气球',
				desc: '分享网络安全与科技生活。',
				link: 'https://blog.qjqq.cn/',
				feed: 'https://blog.qjqq.cn/atom.xml',
				icon: 'https://q2.qlogo.cn/headimg_dl?dst_uin=1645253&spec=640',
				avatar: 'https://q2.qlogo.cn/headimg_dl?dst_uin=1645253&spec=640',
				archs: ['Hexo'],
				date: '2025-08-29',
				comment: '',
			},
			{
				author: 'LiuShen',
				sitenick: '清羽 〄 飞扬',
				title: '清羽飞扬',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: 'https://imgtg.kemeow.top/file/AgACAgUAAyEGAAScqokCAANYaLv-MQNxHKhonGmmdi5IFZc97FQAArPIMRsdkeBVpV_UBn4uX-cBAAMCAANtAAM2BA.webp',
				avatar: 'https://blog.liushen.fun/info/avatar.ico',
				archs: ['Hexo', '服务器'],
				date: '2025-08-29',
				comment: '',
			},
			{
				author: '张洪Heo',
				sitenick: '张洪Heo',
				title: '张洪Heo',
				desc: '分享设计与科技生活',
				link: 'https://blog.zhheo.com/',
				feed: 'https://blog.zhheo.com/atom.xml',
				icon: 'https://img.zhheo.com/i/67d8fa75943e4.webp',
				avatar: 'https://img.zhheo.com/i/67d8fa75943e4.webp',
				archs: ['服务器'],
				date: '2025-08-29',
				comment: '',
			},
			{
				author: 'wallleap',
				sitenick: 'wallleap',
				title: 'wallleap',
				desc: 'Luwang\'s blog',
				link: 'https://myblog.wallleap.cn/',
				feed: '',
				icon: 'https://imgtg.kemeow.top/file/AgACAgUAAyEGAAScqokCAAMmaKqLdVfP6rV0QjlsLLMGBz4AAdF-AAKHwzEbqZxYVV9hJNQl8yumAQADAgADeAADNgQ.webp',
				avatar: 'https://imgtg.kemeow.top/file/AgACAgUAAyEGAAScqokCAAMmaKqLdVfP6rV0QjlsLLMGBz4AAdF-AAKHwzEbqZxYVV9hJNQl8yumAQADAgADeAADNgQ.webp',
				archs: ['GitHub Pages', 'Vercel'],
				date: '2025-08-29',
				comment: '',
			},
			{
				author: '『纸鹿摸鱼处』',
				sitenick: 'zhilu',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				feed: 'https://blog.zhilu.site/atom.xml',
				icon: 'https://www.zhilu.site/api/avatar.png',
				avatar: 'https://www.zhilu.site/api/avatar.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-08-29',
				comment: '',
			},
		],
	},
	{
		name: '『我的好友』',
		desc: '互换友链的好友',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: 'Cynosura',
				sitenick: 'Cynosura',
				title: 'Cynosura',
				desc: 'Trying to light up the dark.',
				link: 'https://cynosura.one/',
				feed: '',
				icon: 'https://img.314926.xyz/images/2025/09/10/Cynosura.webp',
				avatar: 'https://img.314926.xyz/images/2025/09/10/Cynosura.webp',
				archs: ['GitHub Pages', 'Cloudflare'],
				date: '2025-09-10',
				comment: '',
			},
			{
				author: 'ATao',
				sitenick: 'ATao',
				title: 'ATao-Blog',
				desc: '做自己喜欢的事',
				link: 'https://blog.atao.cyou',
				feed: 'https://blog.atao.cyou/atom.xml',
				icon: 'https://cdn.atao.cyou/Web/Avatar.png',
				avatar: 'https://cdn.atao.cyou/Web/Avatar.png',
				archs: ['默认'],
				date: '2025-09-11',
				comment: '',
			},
		],
	},
] satisfies FeedGroup[]
