# workflow name
name: 纸鹿Nuxt博客构建表

# master branch on push, auto run
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.16.0]
    steps:
      # 0️⃣ 强制清空 Runner 遗留（关键：去掉旧 git 对象）
      - name: 0️⃣ 强制清空 Runner 遗留
        run: |
          sudo rm -rf "${{ github.workspace }}"

      # 1️⃣ 重新干净克隆
      - name: 1️⃣ 检查 main 分支
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ 设置 Node.js
      - name: 2️⃣ 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 3️⃣ 安装 pnpm & 依赖
      - name: 3️⃣ 安装插件
        run: |
          npm install -g pnpm@10.13.1
          pnpm install

      # 4️⃣ 构建（跳过 /api/umami）
      - name: 4️⃣ 开始构建
        env:
          LOCAL_GENERATE: true
        run: pnpm generate

      # 5️⃣ 产物大小检查
      - name: 5️⃣ 检查构建产物大小
        run: du -sh .output/public

      # 6️⃣ 单提交推送（无历史，不再携带损坏对象）
      - name: 6️⃣ 推送到仓库（单提交，无历史）
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.nuxttoken }}
          repository-name: Kemeow815/blog-v3-static
          branch: main
          folder: .output/public
          single-commit: true
          commit-message: "${{ github.event.head_commit.message }}"